// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaivsyxvtpmottrhqzvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhaXZzeXh2dHBtb3R0cmhxenZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzAxNDksImV4cCI6MjA2MDA0NjE0OX0.W92kptk5RVqpb5xuSrE5ttqann7qKl-hb7fGcXFldQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);